name: Terraform Apply to STG Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform-apply-stg:
    name: "Apply to STG"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN_STG }}

      - name: Terraform Format
        id: fmt
        run:  |
          cd stg
          terraform fmt -check
        
      - name: Terraform Init
        id: init
        run:  |
          cd stg
          terraform init
          
      - name: Terraform Apply (STG)
        run: |
          cd stg
          terraform init
          terraform apply tfplan
