name: "Snowflake Terraform Demo Workflow"

on:
  push:
    branches:
      - main

jobs:
  snowflake-terraform-demo:
    name: "Snowflake Terraform Demo Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup working directory
        run: cd stg

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN_STG }}

      - name: Terraform Format
        id: fmt
        run: |
          cd stg
          terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          cd stg
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd stg
          terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: |
          cd stg
          terraform apply -auto-approve
        env:
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
